Docker compose removed
* docker compose no longer used to launch fresnel

* fresnel.env renamed to fresnel.conf

* Local user option support and new kill options.

* fresnel-sshd nohup.out is now logged in fresnel-host/logs

diff --git a/fresnel-start b/fresnel-start
--- a/fresnel-start
+++ b/fresnel-start
@@ -2,7 +2,9 @@
 set -euo pipefail
 if [ "${DEBUG:-false}" != false ]; then set -x; fi
 cd $(dirname $0)
-. fresnel.env
+. fresnel.conf
+
+export DOCKER_CLI_HINTS=false
 
 determineTimezone() {
   # Guess which timezone
@@ -21,19 +23,128 @@ doSomethingWithX11() {
   if /usr/bin/which xhost > /dev/null 2>&1
   then
     export INSTALL_X_TOOLS=true
-    echo "X11 tools will be installed in Fresnel."
+    echo "X11 tools will be installed in Fresnel"
   fi
 }
 
 startFresnelSshd() {
-  echo "Starting Fresnel sshd"
+  echo "Starting Fresnel SSH daemon"
   ./fresnel-host/bin/fresnel-sshd
 }
 
-determineTimezone
-doSomethingWithX11
-startFresnelSshd
 
-docker compose build $@
-docker compose up --detach --force-recreate
+buildFresnelImage() {
+  docker build \
+    --tag $FRESNEL_SESSION_ID \
+    --build-arg FRESNEL_USER_ID=$FRESNEL_USER_ID \
+    --build-arg FRESNEL_TIMEZONE=$FRESNEL_TIMEZONE \
+    --build-arg INSTALL_X_TOOLS=${INSTALL_X_TOOLS:-false} \
+   .
+}
+
+
+findFresnelInstance() {
+  docker ps --filter Name=^/$FRESNEL_SESSION_ID\$ --quiet $@
+}
+
+
+shouldWeMurderIt() {
+  local id="${1:-}"
+  if [ -z "${id:-}" ]; then return 0; fi
+  case "${FRESNEL_KILL,,}" in
+    yes|true) return 0;;
+    no|false) return 1;;
+  esac
+  while [ true ]
+  do
+    read -p "Fresnel session $FRESNEL_SESSION_ID is running. Kill $FRESNEL_SESSION_ID? " KILL_IT
+    case "${KILL_IT,,}" in
+      y*) return 0;;
+      n*) return 1;;
+    esac
+  done
+}
+
+
+stopFresnelInstance() {
+  local id
+  id=$(findFresnelInstance)
+  if ! shouldWeMurderIt $id
+  then
+    echo "Fresnel $FRESNEL_SESSION_ID is already running. Aborting."
+    exit 0
+  fi
+  while [ -n "${id:-}" ]
+  do
+    echo "Killing container $id"
+    docker kill $id > /dev/null
+    sleep 0.1
+    id=$(findFresnelInstance)
+  done
+  id=$(findFresnelInstance --all)
+  if [ -n "${id:-}" ]
+  then
+    echo "Removing container $id"
+    docker rm $id > /dev/null
+  fi
+}
+
+
+dockerPortOptions() {
+  case "${FRESNEL_PORTS:-default}" in
+    default) FRESNEL_PORTS=${FRESNEL_DEFAULT_PORTS[@]};;
+    none) return;;
+  esac
+  for p in ${FRESNEL_PORTS}; do echo --publish $p; done
+}
+
+
+startFresnelInstance() {
+  echo "Starting Fresnel"
+  docker run \
+    --privileged \
+    --detach \
+    --name $FRESNEL_SESSION_ID \
+    --hostname $FRESNEL_SESSION_ID \
+    --user dev \
+    --workdir /home/dev \
+    --env USER=dev \
+    --env HOST_USER=$USER \
+    --env TERM=$TERM \
+    --env GIT_CEILING_DIRECTORIES=/va:/home/dev \
+    --env DISPLAY=host.docker.internal:0 \
+    $(dockerPortOptions) \
+    --volume .:/fresnel-dev \
+    --volume /var/run/docker.sock:/var/run/docker.sock \
+    --volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
+    --volume $HOME/.fresnel/home:/home/dev \
+    --volume $HOME/.m2/repository:/repository \
+    --volume $FRESNEL_GITHUB_REPO_DIR:/va \
+    --volume $HOME/Downloads:/Downloads \
+    $FRESNEL_SESSION_ID
+}
+
+
+startFsh() {
+  if [ "$FRESNEL_FSH_ON_START" != "true" ]
+  then
+    echo "Login into Fresnel with $FRESNEL_HOME/fsh"
+    return
+  fi
+  echo "Logging in to Fresnel ..."
+  $FRESNEL_HOME/fsh
+}
+
+main() {
+  echo "Starting Fresnel session $FRESNEL_SESSION_ID"
+  determineTimezone
+  doSomethingWithX11
+  stopFresnelInstance
+  buildFresnelImage
+  startFresnelSshd
+  startFresnelInstance
+  startFsh
+}
+
+main
 
